<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/api.proto

namespace Dkms\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dkms.models.GenerateRandomResponse</code>
 */
class GenerateRandomResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Random = 1;</code>
     */
    private $Random = '';
    /**
     * Generated from protobuf field <code>string RequestId = 2;</code>
     */
    private $RequestId = '';

    public function __construct() {
        \GPBMetadata\Protobuf\Protos\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes Random = 1;</code>
     * @return string
     */
    public function getRandom()
    {
        return $this->Random;
    }

    /**
     * Generated from protobuf field <code>bytes Random = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRandom($var)
    {
        GPBUtil::checkString($var, False);
        $this->Random = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RequestId = 2;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->RequestId;
    }

    /**
     * Generated from protobuf field <code>string RequestId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestId = $var;

        return $this;
    }

}

